# Generated by Django 5.2.1 on 2025-08-06 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='title',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
