# Generated by Django 5.2.1 on 2025-08-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_todoitem_title_alter_todoitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='title',
            field=models.CharField(default='Untitled Todo', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='description',
            field=models.TextField(default='Untitled Todo', max_length=500),
        ),
    ]
